PRETRAIN:
  ENABLE: false
TRAIN:
  ENABLE: true
  DATASET:                          # !!@1
  BATCH_SIZE: 128
  LOG_FILE: training_log.log
  LOSS_FUNC: cross_entropy
  EVAL_PERIOD: 5
  NUM_FOLDS: 30
  AUTO_RESUME: true
  CHECKPOINT_PERIOD: 10
  CHECKPOINT_FILE_PATH: ""          # !!@2
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_INFLATE: false
  FINE_TUNE: false
  ONLY_LINEAR: false
TEST:
  ENABLE: false                     # !!@3
  DATASET:                          # !!@3
  BATCH_SIZE: 128
  NUM_SPATIAL_CROPS: 1
  SPATIAL_CROPS: cc
  NUM_ENSEMBLE_VIEWS: 1
  LOG_FILE: val.log
  CHECKPOINT_FILE_PATH: ""
  CHECKPOINT_TYPE: pytorch
  AUTOMATIC_MULTI_SCALE_TEST: true
DATA:
  DATA_ROOT_DIR: 
  ANNO_DIR: 
  NUM_INPUT_FRAMES: 16
  NUM_INPUT_CHANNELS: 3
  SAMPLING_MODE: interval_based
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [168, 224]
  TRAIN_CROP_SIZE: 112
  TEST_SCALE: 224
  TEST_CROP_SIZE: 112
  MEAN: [0.45, 0.45, 0.45]
  STD: [0.225, 0.225, 0.225]
  MULTI_LABEL: false
  ENSEMBLE_METHOD: sum
  FPS: 30
  TARGET_FPS: 30
OPTIMIZER:
  BASE_LR: 0.002
  LR_POLICY: cosine
  MAX_EPOCH: 300
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-3
  WARMUP_EPOCHS: 10
  WARMUP_START_LR: 0.0002
  OPTIM_METHOD: adam
  DAMPENING: 0.0
  NESTEROV: true
BN:
  WEIGHT_DECAY: 0.0
  EPS: 1e-3
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: false
  ENABLE_MULTI_THREAD_DECODE: true
NUM_GPUS: 8
SHARD_ID: 0
NUM_SHARDS: 1
RANDOM_SEED: 0
OUTPUT_DIR: 
OUTPUT_CFG_FILE: configuration.log
LOG_PERIOD: 10
DIST_BACKEND: nccl
LOG_MODEL_INFO: true
LOG_CONFIG_INFO: true
AUGMENTATION:
  COLOR_AUG: true
  BRIGHTNESS: 0.5
  CONTRAST: 0.5
  SATURATION: 0.5
  HUE: 0.25
  GRAYSCALE: 0.3
  CONSISTENT: true
  SHUFFLE: true
  GRAY_FIRST: true
  RATIO: [0.857142857142857, 1.1666666666666667]
  USE_GPU: true
PAI: false