TASK_TYPE: classification
PRETRAIN:
  ENABLE: false
LOCALIZATION:
  ENABLE: false
TRAIN:
  ENABLE: false
  DATASET:
  BATCH_SIZE: 128
  LOG_FILE: training_log.log
  EVAL_PERIOD: 10
  NUM_FOLDS: 1
  AUTO_RESUME: true
  CHECKPOINT_PERIOD: 10
  CHECKPOINT_FILE_PATH: ""
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_INFLATE: false
  CHECKPOINT_PRE_PROCESS:
    ENABLE: false
  FINE_TUNE: false
  ONLY_LINEAR: false
  LR_REDUCE: false
  TRAIN_VAL_COMBINE: false
TEST:
  ENABLE: false
  DATASET:
  BATCH_SIZE: 100
  NUM_SPATIAL_CROPS: 1
  SPATIAL_CROPS: cc
  NUM_ENSEMBLE_VIEWS: 1
  LOG_FILE: val.log
  CHECKPOINT_FILE_PATH: ""
  CHECKPOINT_TYPE: pytorch
  AUTOMATIC_MULTI_SCALE_TEST: true 
VISUALIZATION:
  ENABLE: false
  NAME: ""
  FEATURE_MAPS:
    ENABLE: false
    BASE_OUTPUT_DIR: ""
SUBMISSION:
  ENABLE: false
  SAVE_RESULTS_PATH: "test.json"
DATA:
  DATA_ROOT_DIR: /data_root/
  ANNO_DIR: /anno_dir/
  NUM_INPUT_FRAMES: 16
  NUM_INPUT_CHANNELS: 3
  SAMPLING_MODE: interval_based
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [168, 224]
  TRAIN_CROP_SIZE: 112
  TEST_SCALE: 224
  TEST_CROP_SIZE: 112
  MEAN: [0.45, 0.45, 0.45]
  STD: [0.225, 0.225, 0.225]
  MULTI_LABEL: false
  ENSEMBLE_METHOD: sum
  TARGET_FPS: 30
  MINUS_INTERVAL: false
MODEL:
  NAME: 
  EMA:
    ENABLE: false
    DECAY: 0.99996
VIDEO:
  BACKBONE:
    DEPTH: 
    META_ARCH: 
    NUM_FILTERS: 
    NUM_INPUT_CHANNELS: 3
    NUM_OUT_FEATURES: 
    KERNEL_SIZE: 
    DOWNSAMPLING: 
    DOWNSAMPLING_TEMPORAL: 
    NUM_STREAMS: 1
    EXPANSION_RATIO: 2
    BRANCH:
      NAME: 
    STEM:
      NAME: 
    NONLOCAL:
      ENABLE: false
      STAGES: [5]
      MASK_ENABLE: false
    INITIALIZATION: 
  HEAD:
    NAME: BaseHead
    ACTIVATION: softmax
    DROPOUT_RATE: 0
    NUM_CLASSES:
OPTIMIZER:
  ADJUST_LR: false
  BASE_LR: 0.002
  LR_POLICY: cosine
  MAX_EPOCH: 300
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-3
  WARMUP_EPOCHS: 10
  WARMUP_START_LR: 0.0002
  OPTIM_METHOD: adam
  DAMPENING: 0.0
  NESTEROV: true
BN:
  WB_LOCK: false
  FREEZE: false
  WEIGHT_DECAY: 0.0
  MOMENTUM: 0.1
  EPS: 1e-5
  SYNC: false
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: false
  ENABLE_MULTI_THREAD_DECODE: true
  COLLATE_FN: 
NUM_GPUS: 8
SHARD_ID: 0
NUM_SHARDS: 1
RANDOM_SEED: 0
OUTPUT_DIR: output/
OUTPUT_CFG_FILE: configuration.log
LOG_PERIOD: 10
DIST_BACKEND: nccl
LOG_MODEL_INFO: true
LOG_CONFIG_INFO: true
OSS:
  ENABLE: false
  KEY: 
  SECRET:    
  ENDPOINT: 
  CHECKPOINT_OUTPUT_PATH:                   # !!@7
  SECONDARY_DATA_OSS: 
    ENABLE: false
    KEY: 
    SECRET: 
    ENDPOINT: 
    BUCKETS: [""]
AUGMENTATION:
  COLOR_AUG: false
  BRIGHTNESS: 0.5
  CONTRAST: 0.5
  SATURATION: 0.5
  HUE: 0.25
  GRAYSCALE: 0.3
  CONSISTENT: true
  SHUFFLE: true
  GRAY_FIRST: true
  RATIO: [0.857142857142857, 1.1666666666666667]
  USE_GPU: false
  MIXUP: 
    ENABLE: false
    ALPHA: 0.0
    PROB: 1.0
    MODE: batch
    SWITCH_PROB: 0.5
  CUTMIX: 
    ENABLE: false
    ALPHA: 0.0
    MINMAX: 
  RANDOM_ERASING:
    ENABLE: false
    PROB: 0.25
    MODE: const
    COUNT: [1, 1]
    NUM_SPLITS: 0
    AREA_RANGE: [0.02, 0.33]
    MIN_ASPECT: 0.3
  LABEL_SMOOTHING: 0.0
  SSV2_FLIP: false
PAI: false