_BASE: ../tada2d_k400.yaml
TRAIN:
  FINE_TUNE: true
  IMAGENET_INIT: true
  CHECKPOINT_FILE_PATH: "" # pretrained imagenet weights
DATA:
  SAMPLING_RATE: 8
  NUM_INPUT_FRAMES: 8
OUTPUT_DIR: output/tada2d_8x8_k400