_BASE: ../csn_ek100_submission.yaml
TRAIN:
  CHECKPOINT_FILE_PATH: ./checkpoints/csn152_pt_k700_ft_ek100_32x224x224_4452_public.pyth
  BATCH_SIZE: 256
TEST:
  BATCH_SIZE: 256
OUTPUT_DIR: output/csn_ek100_submit