MODEL:
  NAME: SlowFast_4x16
VIDEO:
  BACKBONE:
    DEPTH: 50
    META_ARCH: Slowfast
    NUM_FILTERS: [64, 256, 512, 1024, 2048]
    NUM_INPUT_CHANNELS: 3
    NUM_OUT_FEATURES: 2048
    KERNEL_SIZE: [
      [
        [1, 7, 7],
        [1, 3, 3],
        [1, 3, 3],
        [1, 3, 3],
        [1, 3, 3],
      ],
      [
        [5, 7, 7],
        [1, 3, 3],
        [1, 3, 3],
        [1, 3, 3],
        [1, 3, 3],
      ],
    ]
    DOWNSAMPLING: [true, false, true, true, true]
    DOWNSAMPLING_TEMPORAL: [false, false, false, false, false]
    TEMPORAL_CONV_BOTTLENECK:
      [
        [false, false, false, true, true], # slow branch,
        [false, true, true, true, true]    # fast branch
      ]
    NUM_STREAMS: 1
    EXPANSION_RATIO: 4
    BRANCH:
      NAME: SlowfastBranch
    STEM:
      NAME: DownSampleStem
    SLOWFAST:
      MODE: slowfast
      ALPHA: 8
      BETA: 8             # slow fast channel ratio
      CONV_CHANNEL_RATIO: 2
      KERNEL_SIZE: 5
      FUSION_CONV_BIAS: false
      FUSION_BN: true
      FUSION_RELU: true
    NONLOCAL:
      ENABLE: false
      STAGES: [5]
      MASK_ENABLE: false
  HEAD:
    NAME: SlowFastHead
    ACTIVATION: softmax
    DROPOUT_RATE: 0
    NUM_CLASSES:              # !!!
DATA:
  NUM_INPUT_FRAMES: 32
  SAMPLING_RATE: 2
